version: '1.0'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_AI_API=Undefined
      - REACT_BOT_API=Undefined
      - REACT_DEBUG=false
